### ISSUE TITLE
128x64 Panel

### ISSUE THREAD

**Issue by ustunsoz** [TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper#1]
Thank you for the esphome adapted code, it helps very much.

However my panel size 128x64 (width x height) and scan rate 1/32. The code is running but horizontal rows falling 2 pixel row empty after each displayed row. I have tested many other examples mostly running well but the most successful one is https://www.waveshare.com/w/upload/f/f2/RGB-Matrix-P2-64x64-Demo.zip (sourced from: https://www.waveshare.com/wiki/RGB-Matrix-P2.5-64x64)

obviously I have set with and height in yaml as: 
display:
  - platform: matrix_display
    id: matrix
    width: 128
    height: 64

but if you can suggest any other variable to set I will appreciate .

Thanks in advance

**Comment by ustunsoz** [comment]
the bouncing squares example perfectly works with 128x64

**Comment by TillFleisch** [comment]
Since this is a wrapper for an [existing library](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA), I would advise looking for related issues in the linked repository.

Judging by the bouncing sqaures example you've provided it looks the following configurations statements are not present in your yaml configuration.
```c++
mxconfig.clkphase = false;
mxconfig.gpio.e = 32;
```

Within my wrapper component you can add these configuration statements using the following configuration:

```yaml
display:
  - platform: matrix_display
    id: matrix
    width: 128
    height: 64
    E_pin: 32
    clock_phase: false
```

**Comment by ustunsoz** [comment]
thank you for the reply. It's worked well...
