### ISSUE TITLE
The running line

### ISSUE THREAD

**Issue by mihasybn** [TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper#15]
Hello. I want to thank you for this project. Could you add a running line mode. This option is very lacking. “thanks.

**Comment by TillFleisch** [comment]
I assume you are referring to text which is moving across the screen (such as long sentences).
This feature is independent of this component and should be implemented such that other display components can make use of this as well (in other words: as a change/feature in ESPHome it self). Therefore this issue is not related to this component.
A quick web search revealed [this gist](https://gist.github.com/cnorick/1ad3d61e7e517fb05e1972908b6b607e) which demos scrolling text on a ESPHome display using lambdas.
Note that this solution uses the `update_interval` to determine the scroll speed which may interfer with other things such as animations.
Depending on what you want to build something similar can be achieved on a HUB75 based display.
