### ISSUE TITLE
board connection

### ISSUE THREAD

**Issue by vejvik** [TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper#20]
Hi,
does the board have to be esp32-S3 or any esp32 will do?
in the picture below the panelI see some other blue board under the insulating tape - what is it and what is it for?

thank you for the advice

**Comment by TillFleisch** [comment]
>  does the board have to be esp32-S3 or any esp32 will do?

An ESP32 with less memory than the S3 will do just fine, but be aware of the limitations.
Due to the double buffer, less memory will be available.
See [here](https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA?tab=readme-ov-file#esp32-variants-supported) for more details.

> ... some other blue board ... what is it and what is it for?

As mentioned in the project's readme, the retrofit extension is an ambient light sensor which is used in combination with ESPHome to change the brightness of the display throughout the day.
