### ISSUE TITLE
Chained panels do not work

### ISSUE THREAD

**Issue by hn** [TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper#3]
Thank you very much for your great work!

I have a setup with two 64\*32 panels arranged horizontally (chain_length = 2, so resulting size is 128\*32). Basically it works, but nothing is displayed on the second (the one the right) panel. I added the following patch, then it works:

```
diff --git a/components/matrix_display/matrix_display.h b/components/matrix_display/matrix_display.h
index 2f18df9..e530d72 100644
--- a/components/matrix_display/matrix_display.h
+++ b/components/matrix_display/matrix_display.h
@@ -255,7 +255,7 @@ namespace esphome
       /// @brief brightness value number entities belonging to this matrix display
       std::vector<matrix_display_brightness::MatrixDisplayBrightness *> brightness_values_;

-      int get_width_internal() override { return panel_width_; };
+      int get_width_internal() override { return chain_length_ * panel_width_; };
       int get_height_internal() override { return panel_height_; };

       /**
```

But I don't know if this is the best option. What if the panels are arranged vertically?

**Comment by TillFleisch** [comment]
@hn thank you for pointing out this issue.
That is a valid fix and the issue is an oversight on my part. I only have a single display, thus I did not encounter this issue.

Judging by [this](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/tree/master/examples/ChainedPanels) piece of documentation the underlying library uses a long chain of panels and 'virtual displays' to correct the misalignment of pixels on the up-side-down panels.

Adding support for vertically aligned panels is possible but a separate wrapping component for virtual displays is required (as far as I can tell from looking at the library).

I will fix the issue you've pointed out and I will add a small small note in the readme regarding vertically aligned panels.
Additionally, I will open a separate issue as a 'feature request' for vertically aligned panels/virtual displays.
